// GENERATED by scripts/import-drawio.mjs from official draw.io templates.
// Source: https://github.com/jgraph/drawio/tree/dev/src/main/webapp/templates (© JGraph Ltd, licensed CC BY 4.0).
// Converted to design-canvas skeletons (layout and labels kept; styling simplified). Do not edit by hand.
import type { Template } from "./templates.js";

export const DRAWIO_TEMPLATES: Template[] = [
  {
    "id": "uml-activity",
    "name": "UML activity (swimlanes)",
    "kind": "Flow",
    "description": "Concurrent activities in swimlanes with start/end nodes, decisions and fork/join bars.",
    "guide": "UML activity diagram: one swimlane (frame) per actor or thread; rounded boxes are actions, diamonds are decisions with labeled guards ([yes]/[no]), thick bars are fork/join. Start at a filled start node and end at an end node; flows read top to bottom.",
    "source": "draw.io template \"uml/activity_diagram_1\" (© JGraph Ltd, CC BY 4.0), converted",
    "shapes": [
      {
        "id": "v1",
        "x": 0,
        "y": 0,
        "width": 280,
        "height": 570,
        "type": "frame",
        "label": "Thread 1"
      },
      {
        "id": "v2",
        "type": "ellipse",
        "x": 80,
        "y": 33,
        "width": 70,
        "height": 44,
        "label": "start"
      },
      {
        "id": "v3",
        "x": 60,
        "y": 110,
        "width": 110,
        "height": 50,
        "type": "rectangle",
        "label": "idle"
      },
      {
        "id": "v4",
        "x": 60,
        "y": 220,
        "width": 110,
        "height": 50,
        "type": "rectangle",
        "label": "user action"
      },
      {
        "id": "v5",
        "x": 60,
        "y": 325,
        "width": 110,
        "height": 50,
        "type": "rectangle",
        "label": "post command"
      },
      {
        "id": "v6",
        "x": 280,
        "y": 0,
        "width": 280,
        "height": 570,
        "type": "frame",
        "label": "Thread 2"
      },
      {
        "id": "v7",
        "type": "ellipse",
        "x": 320,
        "y": 33,
        "width": 70,
        "height": 44,
        "label": "start"
      },
      {
        "id": "v8",
        "x": 300,
        "y": 110,
        "width": 110,
        "height": 50,
        "type": "rectangle",
        "label": "idle"
      },
      {
        "id": "v9",
        "x": 300,
        "y": 220,
        "width": 110,
        "height": 50,
        "type": "rectangle",
        "label": "check for\nnew commands"
      },
      {
        "id": "v10",
        "x": 300,
        "y": 325,
        "width": 110,
        "height": 50,
        "type": "rectangle",
        "label": "command queue"
      },
      {
        "id": "v11",
        "x": 430,
        "y": 225,
        "width": 80,
        "height": 40,
        "type": "diamond",
        "label": "queue empty"
      },
      {
        "id": "v12",
        "x": 410,
        "y": 128,
        "width": 50,
        "height": 15,
        "type": "rectangle"
      },
      {
        "id": "v13",
        "x": 420,
        "y": 325,
        "width": 110,
        "height": 50,
        "type": "rectangle",
        "label": "dispatch\ncommand\nworker thread"
      },
      {
        "id": "v14",
        "x": 385,
        "y": 490,
        "width": 100,
        "height": 50,
        "type": "rectangle",
        "label": "critical\nsection",
        "backgroundColor": "#fff9db"
      },
      {
        "id": "v15",
        "x": 525,
        "y": 395,
        "width": 5,
        "height": 45,
        "type": "rectangle"
      },
      {
        "id": "v16",
        "x": 560,
        "y": 0,
        "width": 280,
        "height": 570,
        "type": "frame",
        "label": "Thread 3"
      },
      {
        "id": "v17",
        "x": 650,
        "y": 405,
        "width": 110,
        "height": 50,
        "type": "rectangle",
        "label": "process\ncommand"
      },
      {
        "id": "v18",
        "type": "ellipse",
        "x": 670,
        "y": 493,
        "width": 70,
        "height": 44,
        "label": "end"
      },
      {
        "id": "e1",
        "type": "arrow",
        "start": {
          "id": "v2"
        },
        "end": {
          "id": "v3"
        }
      },
      {
        "id": "e2",
        "type": "arrow",
        "start": {
          "id": "v3"
        },
        "end": {
          "id": "v4"
        }
      },
      {
        "id": "e3",
        "type": "arrow",
        "start": {
          "id": "v4"
        },
        "end": {
          "id": "v5"
        }
      },
      {
        "id": "e4",
        "type": "arrow",
        "start": {
          "id": "v5"
        },
        "end": {
          "id": "v3"
        }
      },
      {
        "id": "e5",
        "type": "arrow",
        "start": {
          "id": "v7"
        },
        "end": {
          "id": "v8"
        }
      },
      {
        "id": "e6",
        "type": "arrow",
        "start": {
          "id": "v8"
        },
        "end": {
          "id": "v9"
        }
      },
      {
        "id": "e7",
        "type": "arrow",
        "start": {
          "id": "v9"
        },
        "end": {
          "id": "v10"
        }
      },
      {
        "id": "e8",
        "type": "arrow",
        "start": {
          "id": "v11"
        },
        "end": {
          "id": "v12"
        },
        "label": "yes"
      },
      {
        "id": "e9",
        "type": "arrow",
        "start": {
          "id": "v11"
        },
        "end": {
          "id": "v13"
        },
        "label": "no"
      },
      {
        "id": "e10",
        "type": "arrow",
        "start": {
          "id": "v9"
        },
        "end": {
          "id": "v11"
        }
      },
      {
        "id": "e11",
        "type": "arrow",
        "start": {
          "id": "v12"
        },
        "end": {
          "id": "v8"
        }
      },
      {
        "id": "e12",
        "type": "line",
        "start": {
          "id": "v10"
        },
        "end": {
          "id": "v14"
        }
      },
      {
        "id": "e13",
        "type": "arrow",
        "start": {
          "id": "v13"
        },
        "end": {
          "id": "v15"
        }
      },
      {
        "id": "e14",
        "type": "arrow",
        "start": {
          "id": "v17"
        },
        "end": {
          "id": "v18"
        }
      },
      {
        "id": "e15",
        "type": "arrow",
        "start": {
          "id": "v5"
        },
        "end": {
          "id": "v10"
        }
      }
    ]
  },
  {
    "id": "uml-state",
    "name": "UML state machine",
    "kind": "Flow",
    "description": "States and transitions, with a composite state container.",
    "guide": "UML state machine: boxes are states (name what the thing IS, not what it does), arrows are transitions labeled 'event [guard] / action'. One initial state, explicit final states, and composite states as frames containing their sub-states.",
    "source": "draw.io template \"uml/state_machine\" (© JGraph Ltd, CC BY 4.0), converted",
    "shapes": [
      {
        "id": "v1",
        "type": "ellipse",
        "x": 80,
        "y": 93,
        "width": 70,
        "height": 44,
        "label": "start"
      },
      {
        "id": "v2",
        "x": 210,
        "y": 275,
        "width": 120,
        "height": 60,
        "type": "rectangle",
        "label": "Activity"
      },
      {
        "id": "v3",
        "x": 210,
        "y": 85,
        "width": 120,
        "height": 60,
        "type": "rectangle",
        "label": "Activity"
      },
      {
        "id": "v4",
        "x": 410,
        "y": 165,
        "width": 120,
        "height": 60,
        "type": "rectangle",
        "label": "Activity"
      },
      {
        "id": "v5",
        "x": 760,
        "y": 275,
        "width": 120,
        "height": 60,
        "type": "rectangle",
        "label": "Activity"
      },
      {
        "id": "v6",
        "x": 490,
        "y": 275,
        "width": 120,
        "height": 60,
        "type": "rectangle",
        "label": "Activity"
      },
      {
        "id": "v7",
        "x": 65,
        "y": 460,
        "width": 930,
        "height": 200,
        "type": "frame",
        "label": "Container"
      },
      {
        "id": "v8",
        "x": 280,
        "y": 525,
        "width": 120,
        "height": 60,
        "type": "rectangle",
        "label": "Activity"
      },
      {
        "id": "v9",
        "type": "ellipse",
        "x": 860,
        "y": 533,
        "width": 70,
        "height": 44,
        "label": "end"
      },
      {
        "id": "v10",
        "type": "ellipse",
        "x": 120,
        "y": 533,
        "width": 70,
        "height": 44,
        "label": "start"
      },
      {
        "id": "v11",
        "x": 465,
        "y": 525,
        "width": 120,
        "height": 60,
        "type": "rectangle",
        "label": "Activity"
      },
      {
        "id": "v12",
        "x": 650,
        "y": 525,
        "width": 120,
        "height": 60,
        "type": "rectangle",
        "label": "Activity"
      },
      {
        "id": "v13",
        "x": 0,
        "y": 0,
        "width": 1050,
        "height": 745,
        "type": "frame",
        "label": "frame"
      },
      {
        "id": "e1",
        "type": "arrow",
        "start": {
          "id": "v4"
        },
        "end": {
          "id": "v5"
        }
      },
      {
        "id": "e2",
        "type": "arrow",
        "start": {
          "id": "v5"
        },
        "end": {
          "id": "v3"
        }
      },
      {
        "id": "e3",
        "type": "arrow",
        "start": {
          "id": "v5"
        },
        "end": {
          "id": "v6"
        }
      },
      {
        "id": "e4",
        "type": "arrow",
        "start": {
          "id": "v7"
        },
        "end": {
          "id": "v5"
        }
      },
      {
        "id": "e5",
        "type": "arrow",
        "start": {
          "id": "v8"
        },
        "end": {
          "id": "v11"
        }
      },
      {
        "id": "e6",
        "type": "arrow",
        "start": {
          "id": "v10"
        },
        "end": {
          "id": "v8"
        }
      },
      {
        "id": "e7",
        "type": "arrow",
        "start": {
          "id": "v11"
        },
        "end": {
          "id": "v12"
        }
      },
      {
        "id": "e8",
        "type": "arrow",
        "start": {
          "id": "v12"
        },
        "end": {
          "id": "v9"
        }
      },
      {
        "id": "e9",
        "type": "arrow",
        "start": {
          "id": "v1"
        },
        "end": {
          "id": "v3"
        }
      },
      {
        "id": "e10",
        "type": "arrow",
        "start": {
          "id": "v3"
        },
        "end": {
          "id": "v4"
        }
      },
      {
        "id": "e11",
        "type": "arrow",
        "start": {
          "id": "v4"
        },
        "end": {
          "id": "v2"
        }
      },
      {
        "id": "e12",
        "type": "arrow",
        "start": {
          "id": "v2"
        },
        "end": {
          "id": "v3"
        }
      },
      {
        "id": "e13",
        "type": "arrow",
        "start": {
          "id": "v2"
        },
        "end": {
          "id": "v6"
        }
      },
      {
        "id": "e14",
        "type": "arrow",
        "start": {
          "id": "v6"
        },
        "end": {
          "id": "v4"
        }
      },
      {
        "id": "e15",
        "type": "arrow",
        "start": {
          "id": "v6"
        },
        "end": {
          "id": "v5"
        }
      },
      {
        "id": "e16",
        "type": "arrow",
        "start": {
          "id": "v7"
        },
        "end": {
          "id": "v2"
        }
      },
      {
        "id": "e17",
        "type": "arrow",
        "start": {
          "id": "v7"
        },
        "end": {
          "id": "v2"
        }
      },
      {
        "id": "e18",
        "type": "arrow",
        "start": {
          "id": "v2"
        },
        "end": {
          "id": "v7"
        }
      }
    ]
  },
  {
    "id": "erd",
    "name": "Entity relationship (tables)",
    "kind": "Data",
    "description": "Tables with primary/foreign keys and the relationships between them.",
    "guide": "Entity-relationship diagram: one box per table/entity, first line the name, then one line per column with PK/FK markers. Arrows are relationships labeled with cardinality (1, 0..1, 1..*, *) at the foreign-key side; name join tables for many-to-many.",
    "source": "draw.io template \"software/entity_relationship\" (© JGraph Ltd, CC BY 4.0), converted",
    "shapes": [
      {
        "id": "v1",
        "x": 260,
        "y": 0,
        "width": 160,
        "height": 112,
        "type": "rectangle",
        "label": "Table\nPK,FK1 row 1\nPK,FK2 row 2\nrow 1"
      },
      {
        "id": "v2",
        "x": 540,
        "y": 14,
        "width": 160,
        "height": 144,
        "type": "rectangle",
        "label": "Table\nPK uniqueId\nrow 1\nrow 2\nrow 3"
      },
      {
        "id": "v3",
        "x": 260,
        "y": 220,
        "width": 160,
        "height": 144,
        "type": "rectangle",
        "label": "Table\nPK uniqueId\nrow 1\nrow 2\nrow 3"
      },
      {
        "id": "v4",
        "x": 550,
        "y": 269,
        "width": 160,
        "height": 144,
        "type": "rectangle",
        "label": "Table\nPK uniqueId\nrow 1\nrow 2\nrow 3"
      },
      {
        "id": "v5",
        "x": 860,
        "y": 134,
        "width": 160,
        "height": 112,
        "type": "rectangle",
        "label": "Table\nPK,FK1 row 1\nPK,FK2 row 2\nrow 1"
      },
      {
        "id": "v6",
        "x": 260,
        "y": 440,
        "width": 160,
        "height": 112,
        "type": "rectangle",
        "label": "Table\nPK,FK1 row 1\nPK,FK2 row 2\nrow 1"
      },
      {
        "id": "v7",
        "x": 860,
        "y": 276,
        "width": 160,
        "height": 112,
        "type": "rectangle",
        "label": "Table\nPK,FK1 row 1\nPK,FK2 row 2\nrow 1"
      },
      {
        "id": "v8",
        "x": 860,
        "y": 410,
        "width": 160,
        "height": 112,
        "type": "rectangle",
        "label": "Table\nPK,FK1 row 1\nPK,FK2 row 2\nrow 1"
      },
      {
        "id": "v9",
        "x": 0,
        "y": 218,
        "width": 160,
        "height": 144,
        "type": "rectangle",
        "label": "Table\nPK uniqueId\nrow 1\nrow 2\nrow 3"
      },
      {
        "id": "e1",
        "type": "arrow",
        "start": {
          "id": "v3"
        },
        "end": {
          "id": "v1"
        }
      },
      {
        "id": "e2",
        "type": "arrow",
        "start": {
          "id": "v6"
        },
        "end": {
          "id": "v3"
        }
      },
      {
        "id": "e3",
        "type": "arrow",
        "start": {
          "id": "v2"
        },
        "end": {
          "id": "v1"
        }
      },
      {
        "id": "e4",
        "type": "arrow",
        "start": {
          "id": "v4"
        },
        "end": {
          "id": "v2"
        }
      },
      {
        "id": "e5",
        "type": "arrow",
        "start": {
          "id": "v6"
        },
        "end": {
          "id": "v4"
        }
      },
      {
        "id": "e6",
        "type": "arrow",
        "start": {
          "id": "v4"
        },
        "end": {
          "id": "v5"
        }
      },
      {
        "id": "e7",
        "type": "arrow",
        "start": {
          "id": "v4"
        },
        "end": {
          "id": "v7"
        }
      },
      {
        "id": "e8",
        "type": "arrow",
        "start": {
          "id": "v4"
        },
        "end": {
          "id": "v8"
        }
      },
      {
        "id": "e9",
        "type": "arrow",
        "start": {
          "id": "v9"
        },
        "end": {
          "id": "v1"
        }
      },
      {
        "id": "e10",
        "type": "arrow",
        "start": {
          "id": "v9"
        },
        "end": {
          "id": "v6"
        }
      }
    ]
  },
  {
    "id": "swimlane-flow",
    "name": "Cross-functional flowchart",
    "kind": "Flow",
    "description": "A process across teams or systems: one lane per role, steps flowing between lanes.",
    "guide": "Cross-functional (swimlane) flowchart: one lane (frame) per role, team or system; each step sits in the lane that owns it. Arrows crossing lanes are hand-offs: label what is handed over. Keep time flowing one way (top to bottom).",
    "source": "draw.io template \"flowcharts/cross_functional_flowchart_1\" (© JGraph Ltd, CC BY 4.0), converted",
    "shapes": [
      {
        "id": "v1",
        "x": 0,
        "y": 0,
        "width": 160,
        "height": 730,
        "type": "frame",
        "label": "Lane 1"
      },
      {
        "id": "v2",
        "x": 20,
        "y": 65,
        "width": 100,
        "height": 60,
        "type": "rectangle",
        "label": "Step"
      },
      {
        "id": "v3",
        "x": 20,
        "y": 155,
        "width": 100,
        "height": 60,
        "type": "rectangle",
        "label": "Step"
      },
      {
        "id": "v4",
        "x": 30,
        "y": 560,
        "width": 100,
        "height": 60,
        "type": "rectangle",
        "label": "Step"
      },
      {
        "id": "v5",
        "x": 160,
        "y": 0,
        "width": 160,
        "height": 730,
        "type": "frame",
        "label": "Lane 2"
      },
      {
        "id": "v6",
        "x": 190,
        "y": 65,
        "width": 100,
        "height": 60,
        "type": "rectangle",
        "label": "Step"
      },
      {
        "id": "v7",
        "x": 320,
        "y": 0,
        "width": 160,
        "height": 730,
        "type": "frame",
        "label": "Lane 3"
      },
      {
        "id": "v8",
        "x": 350,
        "y": 155,
        "width": 100,
        "height": 60,
        "type": "rectangle",
        "label": "Step"
      },
      {
        "id": "v9",
        "x": 360,
        "y": 240,
        "width": 80,
        "height": 60,
        "type": "diamond",
        "label": "Decision?"
      },
      {
        "id": "v10",
        "x": 350,
        "y": 560,
        "width": 100,
        "height": 60,
        "type": "rectangle",
        "label": "Step"
      },
      {
        "id": "v11",
        "x": 480,
        "y": 0,
        "width": 160,
        "height": 730,
        "type": "frame",
        "label": "Lane 4"
      },
      {
        "id": "v12",
        "x": 510,
        "y": 240,
        "width": 100,
        "height": 60,
        "type": "rectangle",
        "label": "Step"
      },
      {
        "id": "v13",
        "x": 520,
        "y": 320,
        "width": 80,
        "height": 60,
        "type": "diamond",
        "label": "Decision?"
      },
      {
        "id": "v14",
        "x": 510,
        "y": 400,
        "width": 100,
        "height": 60,
        "type": "rectangle",
        "label": "Step"
      },
      {
        "id": "v15",
        "x": 510,
        "y": 560,
        "width": 100,
        "height": 60,
        "type": "rectangle",
        "label": "Step"
      },
      {
        "id": "v16",
        "x": 520,
        "y": 640,
        "width": 80,
        "height": 60,
        "type": "diamond",
        "label": "Decision?"
      },
      {
        "id": "v17",
        "x": 640,
        "y": 0,
        "width": 160,
        "height": 730,
        "type": "frame",
        "label": "Lane 5"
      },
      {
        "id": "v18",
        "x": 670,
        "y": 400,
        "width": 100,
        "height": 60,
        "type": "rectangle",
        "label": "Step"
      },
      {
        "id": "v19",
        "x": 670,
        "y": 480,
        "width": 100,
        "height": 60,
        "type": "rectangle",
        "label": "Step"
      },
      {
        "id": "v20",
        "x": 670,
        "y": 560,
        "width": 100,
        "height": 60,
        "type": "rectangle",
        "label": "Step"
      },
      {
        "id": "v21",
        "x": 670,
        "y": 640,
        "width": 100,
        "height": 60,
        "type": "rectangle",
        "label": "Step"
      },
      {
        "id": "v22",
        "x": 800,
        "y": 0,
        "width": 160,
        "height": 730,
        "type": "frame",
        "label": "Lane 6"
      },
      {
        "id": "v23",
        "x": 830,
        "y": 640,
        "width": 100,
        "height": 60,
        "type": "rectangle",
        "label": "Step"
      },
      {
        "id": "e1",
        "type": "arrow",
        "start": {
          "id": "v2"
        },
        "end": {
          "id": "v6"
        }
      },
      {
        "id": "e2",
        "type": "arrow",
        "start": {
          "id": "v6"
        },
        "end": {
          "id": "v3"
        }
      },
      {
        "id": "e3",
        "type": "arrow",
        "start": {
          "id": "v3"
        },
        "end": {
          "id": "v8"
        }
      },
      {
        "id": "e4",
        "type": "arrow",
        "start": {
          "id": "v9"
        },
        "end": {
          "id": "v3"
        }
      },
      {
        "id": "e5",
        "type": "arrow",
        "start": {
          "id": "v13"
        },
        "end": {
          "id": "v3"
        }
      },
      {
        "id": "e6",
        "type": "arrow",
        "start": {
          "id": "v16"
        },
        "end": {
          "id": "v3"
        }
      },
      {
        "id": "e7",
        "type": "arrow",
        "start": {
          "id": "v9"
        },
        "end": {
          "id": "v12"
        }
      },
      {
        "id": "e8",
        "type": "arrow",
        "start": {
          "id": "v16"
        },
        "end": {
          "id": "v21"
        }
      },
      {
        "id": "e9",
        "type": "arrow",
        "start": {
          "id": "v21"
        },
        "end": {
          "id": "v23"
        }
      },
      {
        "id": "e10",
        "type": "arrow",
        "start": {
          "id": "v14"
        },
        "end": {
          "id": "v18"
        }
      },
      {
        "id": "e11",
        "type": "arrow",
        "start": {
          "id": "v20"
        },
        "end": {
          "id": "v10"
        }
      },
      {
        "id": "e12",
        "type": "arrow",
        "start": {
          "id": "v20"
        },
        "end": {
          "id": "v15"
        }
      },
      {
        "id": "e13",
        "type": "arrow",
        "start": {
          "id": "v20"
        },
        "end": {
          "id": "v4"
        }
      },
      {
        "id": "e14",
        "type": "arrow",
        "start": {
          "id": "v4"
        },
        "end": {
          "id": "v15"
        }
      },
      {
        "id": "e15",
        "type": "arrow",
        "start": {
          "id": "v10"
        },
        "end": {
          "id": "v15"
        }
      },
      {
        "id": "e16",
        "type": "arrow",
        "start": {
          "id": "v8"
        },
        "end": {
          "id": "v9"
        }
      },
      {
        "id": "e17",
        "type": "arrow",
        "start": {
          "id": "v12"
        },
        "end": {
          "id": "v13"
        }
      },
      {
        "id": "e18",
        "type": "arrow",
        "start": {
          "id": "v13"
        },
        "end": {
          "id": "v14"
        }
      },
      {
        "id": "e19",
        "type": "arrow",
        "start": {
          "id": "v15"
        },
        "end": {
          "id": "v16"
        }
      },
      {
        "id": "e20",
        "type": "arrow",
        "start": {
          "id": "v18"
        },
        "end": {
          "id": "v19"
        }
      },
      {
        "id": "e21",
        "type": "arrow",
        "start": {
          "id": "v19"
        },
        "end": {
          "id": "v20"
        }
      }
    ]
  }
];
